// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace sudokube.Migrations
{
    [DbContext(typeof(SudokuContext))]
    partial class SudokuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sudoku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("SolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SolvedPuzzle")
                        .IsRequired()
<<<<<<< HEAD
<<<<<<< HEAD
                        .HasMaxLength(81)
                        .HasColumnType("nvarchar(81)");
=======
                        .HasColumnType("nvarchar(max)");
>>>>>>> 81c5a6e7d34ec0b5d44dc23f99b96a8a1204582a
=======
                        .HasColumnType("nvarchar(max)");
>>>>>>> 81c5a6e (feat: db code first, dxDataGrid DevExtreme)

                    b.HasKey("Id");

                    b.ToTable("Sudokus");
                });
#pragma warning restore 612, 618
        }
    }
}
